### ISSUE TITLE
Feature Request: attach custom data

### ISSUE THREAD

**Issue by Gounlaf** [crazycodr/standard-exceptions#17]
Hi,

Can you provide a way to attach custom data to the exceptions, without needing to extends them?

I think about something like this:

```php
use ArrayAccess;

trait WithContext
{
    /**
     * @var ArrayAccess
     */
    protected $context;

    /**
     * @return ArrayAccess
     */
    public function getContext()
    {
        return $this->context;
    }
}
```

Thanks,

Regards.

**Comment by crazycodr** [comment]
Thats a nice addition, i'll work on that this afternoon and cleanup the CI too, i haven't worked on it for some time!

**Comment by crazycodr** [comment]
Hey sorry i didn't have the time to work on this yet, i'm in the middle of a move (Moving saturday) and i also have more work than expected. It ends up more realistic to achieve this early next week. Sorry.

**Comment by crazycodr** [comment]
Hey @Gounlaf, checkout the PR i made. If you think it solves your problem, please respond, i'll merge it and tag the package.
