### ISSUE TITLE
HTTP exceptions should by-default use the semantically correct code.

### ISSUE THREAD

**Issue by MrTrick** [crazycodr/standard-exceptions#2]
Where an HTTP error response needs to be sent back to the client, it would help if it was easier to link exceptions with the right responses. I suggest that
- The default parameter for each HTTPException be set to that error code.
- An `HTTP_CODE` constant be added to each HTTPException class.

Along with #1, this would allow an application to use this pattern:

```
try {
  $app->run();
} catch(HTTPException $e) {
  $code = $e->getCode();
  if ($code < 400 || $code > 599) $code = $e::HTTP_CODE;
  sendAnError($code, $e->getMessage()); //Send back the right semantic response.
} catch(Exception $e) {
  sendAnError(500, $e->getMessage()); //Not sure, send back server error
}
```

**Comment by crazycodr** [comment]
Makes sense, you can open a PR with those changes if you want or wait for me to do it, but right now, i've got A LOT on my shoulders, so i don't know when i'll be able to do them. It shouldn't be a really long PR to create seriously.

**Comment by crazycodr** [comment]
https://github.com/crazycodr/standard-exceptions/tree/version2

**Comment by MrTrick** [comment]
Hey, looks good!  
I read through https://github.com/crazycodr/standard-exceptions/compare/version2 to get an idea of what the changes were.

Couple of things I would suggest that'll make your life easier;
1. 'const' can be overriden. You can set `const HTTP_CODE=-1` in `BaseErrorException`, `const HTTP_CODE=400` in `ClientErrorException` and etc, and override for each concrete class.
2. `getHttpCode()` can be static. You don't need an instance to call it, and you can call static methods as instance methods without any issue.
3. You can reference the HTTP_CODE with `static::HTTP_CODE` - that'll work with all the class heirarchy properly.

I'm happy to put this together as a pull request - just give me a few days. :-)

**Comment by crazycodr** [comment]
I'm still refactoring, don't fork version 2 yet, it's a major WIP. I agree for the static attribute to the function calls but i wouldn't define a const HTTP_CODE = -1 because it breaks/violates Liskov principle a that point. Thats why i have an interface that defines the methods at the low level but the data is not avail until it makes sense to have it.

**Comment by crazycodr** [comment]
@MrTrick Version 2 ready but not merged yet. Tell me what you think!

There might be some slight changes like adding tag interfaces or documentation changes, but overall it is what i had envisioned a few months ago!

**Comment by crazycodr** [comment]
Fixed by https://github.com/crazycodr/standard-exceptions/releases/tag/2.0.0
