### ISSUE TITLE
Feature Request: withContext + from

### ISSUE THREAD

**Issue by Gounlaf** [crazycodr/standard-exceptions#21]
Hi,

With PR #20, we forgot something important: the ability to attach a context **and** attach a previous exception.

I see two solutions:

```php
public static function withContext($context, \Throwable $ex = null,string $message = null, int $code = null)
```

or 

```php
public static function withContext($context, string $message = null, int $code = null, \Throwable $ex = null)
```

The first one introduce a BC Break because the signature order change. The second one doesn't, and it's more like the default ctor

I can make a PR.

Regards,

**Comment by crazycodr** [comment]
I'd go with the later obviously for the BC break reason! This would simply touch your recent additions anyway.
