### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by jvdjay** [crazycodr/standard-exceptions#9]
every time I run your tests through phpunit im getting this parse error:
```
Parse error: syntax error, unexpected ':', expecting ';' or '{' in 
vendor/crazycodr/standard-exceptions/Exceptions/Collection/CollectionException.php on line 22
```

which is stemming from:
`public static function getDefaultMessage(): string
    {
        return static::MESSAGE;
    }
`

pretty much the functionName()**: type** that you add to each method is throwing a parse error. im using php5.6 and that when it comes up.

**Comment by crazycodr** [comment]
Oh darn, sorry i've been using PHP 7.0 for over a year so i just moved the whole library on to 7.0. You should really consider moving away from 5.6 and into the 7.0 branch.

To solve this problem would mean going back to support very old versions which will not happen so you should just fix your version to https://github.com/crazycodr/standard-exceptions/tree/2.1.2.

If you are unsure how to achieve this, just open your `composer.json` file and then put `2.1.2` after the colon where it specifies the name of my package. This way you will be fixed to 2.1.2 which is 5.6 compatible.
